# Generated by Django 3.2.16 on 2023-09-29 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealInitiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата регистрации первого обращения')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО инициатора')),
                ('tab_number', models.CharField(max_length=10, unique=True, verbose_name='ФИО инициатора')),
                ('ratio', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, verbose_name='Рейтинг пользователя')),
            ],
            options={
                'verbose_name': 'Инициатор обращения',
                'verbose_name_plural': ('Инициаторы обращений',),
                'ordering': ('-date_register', 'tab_number'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#FF0000', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_hex_code', message='Недопустимые символы в коде', regex='^#[a-zA-Z0-9]{6}$')], verbose_name='HEX код')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField(auto_created=True, auto_now=True, verbose_name='Время расчета')),
                ('ratio', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Уровень аномалии')),
                ('tag', models.ForeignKey(default='<Неизвестный>', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='anomaly', to='home.tag', verbose_name='Заявитель')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='Текст обращения')),
                ('initial_theme', models.CharField(max_length=300, verbose_name='Тема обращения')),
                ('date_create', models.DateField(verbose_name='Дата создания обращения')),
                ('zno_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Номер ЗНО')),
                ('attachment', models.BooleanField(verbose_name='Наличие вложения')),
                ('mentioned', models.CharField(max_length=150, verbose_name='Упоминание сотрудника или клиента')),
                ('constructive', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Конструктивность обращения')),
                ('initiator', models.ForeignKey(default='<Неизвестный>', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='appeals', to='home.appealinitiator', verbose_name='Заявитель')),
                ('tags', models.ManyToManyField(related_name='appeals', to='home.Tag', verbose_name='Теги')),
            ],
        ),
    ]
