# Generated by Django 3.2.16 on 2023-09-30 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ('zno_id', 'date_create'), 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='appealinitiator',
            options={'ordering': ('-date_register', 'tab_number'), 'verbose_name': 'Инициатор обращения', 'verbose_name_plural': 'Инициаторы обращений'},
        ),
        migrations.AlterModelOptions(
            name='timeseriesanomaly',
            options={'ordering': ('tag', 'ratio'), 'verbose_name': 'Аномалия по тэгам', 'verbose_name_plural': 'Аномалии по тэгам'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='appeal',
            name='processed_message',
            field=models.CharField(blank=True, max_length=300, verbose_name='АВТО: Текст обращения обработанный'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='toxic',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, verbose_name='Токсичность сообщения'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(default=None, max_length=30, verbose_name='Группа тэга'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='constructive',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, verbose_name='Конструктивность обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='home.appealinitiator', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='mentioned',
            field=models.BooleanField(blank=True, verbose_name='Упоминание сотрудника или клиента'),
        ),
        migrations.AlterField(
            model_name='appealinitiator',
            name='tab_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_code', message='Недопустимые символы в коде', regex='^#[a-zA-Z0-9]{6}$')], verbose_name='HEX код'),
        ),
    ]
