# Generated by Django 3.2.16 on 2023-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230930_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='appeals', to='home.Tag', verbose_name='Теги'),
        ),
    ]
